Prepare to major release
fingerprintjs/fingerprintjs-pro-spa pull request #38
Opened 2023-03-07 18:09 UTC by ilfa

2023-03-08 15:11 UTC, JuroUhlar requested changes

2023-03-08 15:11 UTC, JuroUhlar commented on README.md
> +- To learn more about the Fingerprint Pro read our [product documentation](https://dev.fingerprint.com/docs).
```suggestion
- To learn more about Fingerprint Pro read our [product documentation](https://dev.fingerprint.com/docs).
```

2023-03-08 15:11 UTC, JuroUhlar commented on README.md
> +- To learn more about this SDK, there is [Typedoc-generated SDK Reference](https://fingerprintjs.github.io/fingerprintjs-pro-spa) available.
```suggestion
- To learn more about this SDK, there is a [Typedoc-generated SDK Reference](https://fingerprintjs.github.io/fingerprintjs-pro-spa) available.
```

2023-03-08 15:11 UTC, JuroUhlar commented on README.md
> +- To learn more about this SDK, there is [Typedoc-generated SDK Reference](https://fingerprintjs.github.io/fingerprintjs-pro-spa) available.
Also, is it just me or does https://fingerprintjs.github.io/fingerprintjs-pro-spa/ give you a 404 now?

2023-03-09 13:22 UTC, TheUnderScorer approved these changes

2023-03-10 14:29 UTC, merged

2023-03-10 14:31 UTC, ilfa commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@fingerprintjs/fingerprintjs-pro-spa/v/1.0.0)
- [GitHub release](https://github.com/fingerprintjs/fingerprintjs-pro-spa/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-05-02 20:45 UTC, kdawgwilk commented
What breaking changes were actually included in 1.0.0?  It says breaking changes but mentions no breaking changes that we need to be aware of?

2023-05-03 09:41 UTC, JuroUhlar commented
Hm it seems the semantic versioning release process automatically puts a big scary BREAKING CHANGES title on any major version release, which makes sense most of the time but not when you go `0.x` to `1.0` without breaking anything, which I think is the case here. @ilfa There are no actual braking changes, correct?